package support

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	CodeFlareSDKVersion = "0.12.0"
	RayVersion          = "2.23.0"
	RayImage            = "quay.io/modh/ray:2.35.0-py39-cu121"
)
