name: Verify Unit tests

on:
  pull_request:
    paths:
      - 'support/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: v1.21
        
        

    - name: Run unit tests
      run: go test ./support/. -v